# Generated by Django 4.0.5 on 2022-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='button_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
