# Generated by Django 4.0.5 on 2022-07-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_alter_product_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='button_text',
        ),
    ]
