# Generated by Django 4.0.5 on 2022-07-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
