# Generated by Django 4.0.5 on 2022-07-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_product_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='best_seller',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='lorem ipsm'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='hot_deals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='video_URL',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='disp_name',
            field=models.CharField(default='smartpxdisp', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='300$', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(default='smartpx', max_length=255),
        ),
    ]
