# Generated by Django 4.0.5 on 2022-07-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_product_photo_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
