# Generated by Django 4.0.5 on 2022-07-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_remove_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.CharField(default='300$', max_length=10),
        ),
    ]
