# Generated by Django 4.0.6 on 2022-07-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0014_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
