# Generated by Django 4.0.6 on 2022-07-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_remove_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_stripe',
            field=models.IntegerField(default=10),
        ),
    ]
